// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpimuxhszzhgrckdlhav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwaW11eGhzenpoZ3Jja2RsaGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTAyNDQsImV4cCI6MjA2NTA2NjI0NH0.0-92rGTbZUe2cDQZ53TAWzD2peDvUnB7dCRlQ6DPZVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});